# Generated by Django 5.1.6 on 2025-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('city', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('Native', 'Native'), ('Fluent', 'Fluent'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=50),
        ),
    ]
