# Generated by Django 5.1.6 on 2025-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_profile_alter_language_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
