# Generated by Django 5.1.6 on 2025-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
